const ACTION_TYPES = {
  CHANGE_LEVEL_HEIGHT: 'CHANGE_LEVEL_HEIGHT',
  CHANGE_MAIN_RATE: 'CHANGE_MAIN_RATE',
  CHANGE_MAIN_WIDTH: 'CHANGE_MAIN_WIDTH',
  RESIZE_WIDTH: 'RESIZE_WIDTH',
  RESIZE_HEIGHT: 'RESIZE_HEIGHT',
  ADD_TANK: 'ADD_TANK',
  DELETE_TANK: 'DELETE_TANK',
};
export default ACTION_TYPES;
